# Generated by Django 3.1.3 on 2020-11-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='post_images', to='posts.PostImage'),
        ),
    ]
