# Generated by Django 3.1.3 on 2020-11-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
